name: PowerShell Linter
on: [push] # This means "Run this every time I save"

jobs:
  check-script:
    runs-on: ubuntu-latest # This is a computer in the cloud GitHub gives you
    steps:
      - uses: actions/checkout@v4 # Copy your code to that cloud computer
      - name: Run a simple test
        shell: pwsh
        - name: Validate Packaging Standards
        shell: pwsh
        run: |
          if (Test-Path "README.md") {
              Write-Host "Standard Met: README exists."
          } else {
              Write-Error "CRITICAL FAILURE: README.md is missing!"
              exit 1
          }